version: '3'
services:
  postgre-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volume:/var/lib/postgresql/data
  business-api:
    depends_on:
      - "postgre-server"
    build:
      context: ./business-api
      dockerfile: Dockerfile.dev
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgre-server:5432/postgres"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  gateway-api:
    depends_on:
      - "business-api"
    build:
      context: ./gateway-api
      dockerfile: Dockerfile.dev
    environment:
      BUSINESS_API_HOSTNAME: "http://business-api:8080"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"